/*
 * stock_ticker.c
 * Sega Genesis stock ticker using SGDK + MegaWiFi ESP32-C3
 *
 * Displays scrolling ticker tape on plane B, static prices on plane A.
 * Polls Finnhub /quote endpoint over HTTPS every ~10 seconds (round-robin).
 *
 * Build: SGDK with mw-api linked in. Set MW_BUFLEN to at least 512.
 *
 * HTTPS: TLS handled by the firmware's built-in Mozilla CA bundle
 * (CONFIG_MBEDTLS_CERTIFICATE_BUNDLE=y). No custom cert upload needed.
 */

#include <genesis.h>
#include <task.h>
#include <string.h>
#include "ext/mw/megawifi.h"
#include "ext/mw/mw-msg.h"
#include "nasdaq_bg.h"   /* generated by rescomp from res/nasdaq_bg.res */

#ifndef MW_MS_TO_FRAMES
#define MW_MS_TO_FRAMES(ms) (((ms) * 60 + 999) / 1000) /* ms -> 60Hz frames */
#endif
/* no stdlib.h available in SGDK headers; provide minimal prototypes */
long atol(const char *nptr);

static char *find_char(const char *s, char c)
{
    while (*s) { if (*s == c) return (char*)s; s++; }
    return NULL;
}

static const char *find_substr(const char *hay, const char *needle)
{
    if (!*needle) return hay;
    while (*hay) {
        const char *h = hay;
        const char *n = needle;
        while (*h && *n && (*h == *n)) { h++; n++; }
        if (*n == '\0') return hay;
        hay++;
    }
    return NULL;
}

/* -------------------------------------------------------------------------
 * Config
 * ---------------------------------------------------------------------- */
#define MS_TO_FRAMES(ms)    ((((ms) * 60 / 500) + 1) / 2)
#define FPS                 60
#define AP_SLOT             0
#define AP_SSID             "YourSSID"
#define AP_PASS             "YourPassword"
/* 10s per ticker × 6 tickers = 60s full cycle = 6 calls/min (limit: 60/min) */
#define UPDATE_FRAMES       (FPS * 10)
#define MAX_TICKERS         6
#define TICKER_SCROLL_SPEED 1
#define COUNTDOWN_ROW       2               /* "Next Update: Xs" row         */
#define COUNTDOWN_COL       2               /* under "M" in MegaWifi         */
#define STATUS_ROW          3               /* error-only status line        */
/* Prices centered between STATUS_ROW+1 and MARQUEE_ROW-1, shifted 1 row up. */
#define PRICE_START_ROW     9
#define PRICE_ROW_STRIDE    2
#define MARQUEE_ROW         27              /* bottom row of the screen      */
#ifndef FINNHUB_TOKEN
#define FINNHUB_TOKEN   "REPLACE_WITH_YOUR_TOKEN"
#warning "FINNHUB_TOKEN not defined; using placeholder will fail authentication"
#endif
#define FINNHUB_URL_FMT "https://finnhub.io/api/v1/quote?symbol=%s&token=%s"

/* -------------------------------------------------------------------------
 * Ticker data
 * ---------------------------------------------------------------------- */
typedef struct {
    const char *symbol;
    s32         price_cents;
    s32         prev_close_cents;
    bool        valid;
    char        timestamp[12];   /* "HH:MM:SS\0" (CST) */
} TickerEntry;

static TickerEntry tickers[MAX_TICKERS] = {
    { "ORCL",  0, 0, false, "" },
    { "NVDA",  0, 0, false, "" },
    { "AMZN",  0, 0, false, "" },
    { "IBM",   0, 0, false, "" },
    { "MSFT",  0, 0, false, "" },
    { "GOOGL", 0, 0, false, "" },
};

/* Per-ticker symbol palette — matched to corporate logo colours.
 * Four working palettes (all use foreground slot index 15 within palette):
 *   PAL0 = white   PAL1 = green   PAL2 = red   PAL3 = cyan
 *
 * GOOGL gets per-letter multi-colour treatment (see draw_googl_symbol).
 * Its entry here is PAL0 (unused — draw_price_panel skips it for GOOGL). */
static const u8 ticker_sym_pal[MAX_TICKERS] = {
    PAL2, /* ORCL  — Oracle red          */
    PAL1, /* NVDA  — Nvidia green        */
    PAL0, /* AMZN  — white (no orange)   */
    PAL3, /* IBM   — IBM blue/cyan       */
    PAL3, /* MSFT  — Microsoft cyan      */
    PAL0, /* GOOGL — multi (see below)   */
};

/* draw_googl_symbol() — renders "GOOGL" letter-by-letter in Google brand colours.
 *   G=cyan(PAL3)  O=red(PAL2)  O=white(PAL0)  G=cyan(PAL3)  L=green(PAL1) */
static void draw_googl_symbol(u8 col, u8 row)
{
    static const char letters[] = "GOOGL";
    static const u8   pals[]    = { PAL3, PAL2, PAL0, PAL3, PAL1 };
    char ch[2] = { 0, 0 };
    u8 i;
    for (i = 0; i < 5; i++) {
        ch[0] = letters[i];
        VDP_setTextPalette(pals[i]);
        VDP_drawText(ch, col + i, row);
    }
}

/* -------------------------------------------------------------------------
 * Scrolling marquee state
 * ---------------------------------------------------------------------- */
static char  marquee_buf[2][256];
static u8    marquee_pal_buf[2][256];   /* palette per character */
static u8    marquee_read_idx = 0;
static volatile bool marquee_pending = false;
static u16   scroll_x = 0;

/* -------------------------------------------------------------------------
 * NASDAQ diagonal background scroll state
 * HSCROLL_TILE mode: bgb_hscroll[] holds -bg_sx for every tile row of BG_B.
 * BG_A rows 0-26 stay at 0; BG_A row 27 (marquee) scrolls independently.
 * ---------------------------------------------------------------------- */
static s16 bg_sx = 0;
static s16 bg_sy = 0;
static s16 bgb_hscroll[32];  /* uniform horizontal scroll for all BG_B tile rows */

/* -------------------------------------------------------------------------
 * MegaWiFi shared command buffer
 * ---------------------------------------------------------------------- */
static uint16_t cmd_buf[MW_BUFLEN/2];

/* Firmware version */
static uint8_t fw_major = 0, fw_minor = 0;
static char fw_variant_buf[32] = "?";
static char *fw_variant = fw_variant_buf;

/* -------------------------------------------------------------------------
 * status_clear() / status_err()
 * STATUS_ROW is blank during normal operation; red text on error.
 * ---------------------------------------------------------------------- */
static void status_clear(void)
{
    VDP_setTextPalette(PAL0);
    VDP_drawText("                                        ", 0, STATUS_ROW);
}

static void status_err(const char *msg)
{
    char buf[42];
    uint8_t i = 0;
    while (msg[i] && i < 39) { buf[i] = msg[i]; i++; }
    while (i < 40) buf[i++] = ' ';
    buf[40] = '\0';
    VDP_setTextPalette(PAL2); /* red */
    VDP_drawText(buf, 0, STATUS_ROW);
    VDP_setTextPalette(PAL0);
    VDP_waitVSync();
}

/* Used only during init for one-time progress messages */
static void status_info(const char *msg)
{
    char buf[42];
    uint8_t i = 0;
    while (msg[i] && i < 39) { buf[i] = msg[i]; i++; }
    while (i < 40) buf[i++] = ' ';
    buf[40] = '\0';
    VDP_setTextPalette(PAL0);
    VDP_drawText(buf, 0, STATUS_ROW);
    VDP_waitVSync();
}

/* -------------------------------------------------------------------------
 * draw_countdown() — row COUNTDOWN_ROW, col COUNTDOWN_COL, white (PAL0)
 * ---------------------------------------------------------------------- */
static void draw_countdown(u16 frame)
{
    int secs = (int)((UPDATE_FRAMES - frame) / FPS);
    char buf[24];
    sprintf(buf, "Next Update: %2ds  ", secs);
    VDP_setTextPalette(PAL0); /* white */
    VDP_drawText(buf, COUNTDOWN_COL, COUNTDOWN_ROW);
}

/* -------------------------------------------------------------------------
 * Minimal JSON number parser
 * ---------------------------------------------------------------------- */
static s32 parse_json_price_cents(const char *body, const char *key)
{
    const char *p = find_substr(body, key);
    if (!p) return 0x7FFFFFFF;
    p = find_char(p, ':');
    if (!p) return 0x7FFFFFFF;
    p++;
    while (*p == ' ') p++;
    int sign = 1;
    if (*p == '-') { sign = -1; p++; }
    long ipart = 0;
    while (*p >= '0' && *p <= '9') { ipart = ipart * 10 + (*p - '0'); p++; }
    long frac = 0; int fdig = 0;
    if (*p == '.') {
        p++;
        while (*p >= '0' && *p <= '9' && fdig < 2) { frac = frac * 10 + (*p - '0'); fdig++; p++; }
        while (*p >= '0' && *p <= '9') p++;
    }
    if (fdig == 1) frac *= 10;
    return sign * (s32)(ipart * 100 + frac);
}

/* -------------------------------------------------------------------------
 * fetch_quote_https()
 * Status line is silent on success; shows error in red on failure.
 * ---------------------------------------------------------------------- */
static void fetch_quote_https(u8 idx)
{
    uint8_t ch = MW_HTTP_CH;
    int16_t cr = 0, ue = 0, me = 0, oe = 0, re = 0;
    int16_t http_status = 0;
    int16_t recv_len = 0;
    uint32_t content_len = 0;
    char url[160];
    char dbg[42];
    s32 price = 0x7FFFFFFF, prev = 0x7FFFFFFF;
    const char *sym = tickers[idx].symbol;

    cr = mw_http_cleanup();

    sprintf(url, FINNHUB_URL_FMT, sym, FINNHUB_TOKEN);
    ue = mw_http_url_set(url);
    if (ue) goto done;

    me = mw_http_method_set(MW_HTTP_METHOD_GET);
    if (me) goto done;

    mw_http_header_add("Accept", "application/json");

    oe = mw_http_open(0);
    if (oe) goto done;

    http_status = mw_http_finish(&content_len, MS_TO_FRAMES(12000));
    if (http_status < 200 || http_status >= 300 || content_len == 0) {
        mw_http_cleanup();
        goto done;
    }

    recv_len = (content_len < (uint32_t)(MW_BUFLEN - 2))
             ? (int16_t)content_len : (int16_t)(MW_BUFLEN - 2);
    re = mw_recv_sync(&ch, (char*)cmd_buf, &recv_len, MS_TO_FRAMES(12000));
    /* Parse BEFORE cleanup — cleanup reuses cmd_buf */
    if (!re && recv_len > 0) {
        ((char*)cmd_buf)[recv_len] = '\0';
        price = parse_json_price_cents((char*)cmd_buf, "\"c\"");
        prev  = parse_json_price_cents((char*)cmd_buf, "\"pc\"");
    }
    mw_http_cleanup();

done:
    {
        bool ok = (ue == 0 && me == 0 && oe == 0 &&
                   http_status >= 200 && http_status < 300 &&
                   re == 0 && recv_len > 0 &&
                   price != 0x7FFFFFFF && prev != 0x7FFFFFFF);
        if (ok) {
            status_clear();
        } else {
            sprintf(dbg, "[%-5s] c=%d u=%d m=%d o=%d f=%d r=%d",
                    sym, (int)cr, (int)ue, (int)me, (int)oe,
                    (int)http_status, (int)re);
            status_err(dbg);
        }
    }

    if (ue || me || oe || re || recv_len <= 0 ||
        price == 0x7FFFFFFF || prev == 0x7FFFFFFF ||
        http_status < 200 || http_status >= 300)
        return;

    tickers[idx].price_cents      = price;
    tickers[idx].prev_close_cents = prev;
    tickers[idx].valid            = true;
    /* Stamp the CST time this quote arrived */
    {
        uint32_t dt[2] = {0, 0};
        char *ts = mw_date_time_get(dt);
        /* ts: "WWW MMM DD HH:MM:SS YYYY" — extract HH:MM:SS at offset 11 */
        if (ts && ts[11] && ts[16]) {
            uint8_t hh = (uint8_t)((ts[11]-'0')*10 + (ts[12]-'0'));
            const char *ampm = (hh >= 12) ? "PM" : "AM";
            if (hh == 0) hh = 12;
            else if (hh > 12) hh -= 12;
            /* "HH:MM AM\0" = 9 bytes, fits in timestamp[12] */
            sprintf(tickers[idx].timestamp, "%2d:%c%c %s",
                    (int)hh, ts[14], ts[15], ampm);
        }
    }
}

static void fetch_quote(u8 idx) { fetch_quote_https(idx); }

/* -------------------------------------------------------------------------
 * rebuild_marquee()
 * ---------------------------------------------------------------------- */
static void rebuild_marquee(void)
{
    u8    write_idx = 1 - marquee_read_idx;
    char *p   = marquee_buf[write_idx];
    u8   *pp  = marquee_pal_buf[write_idx];
    u8 i, j, n, sym_len, white_len;

    for (i = 0; i < MAX_TICKERS; i++) {
        sym_len   = (u8)strlen(tickers[i].symbol);
        white_len = 1 + sym_len + 1; /* leading space + symbol + ':' */

        if (!tickers[i].valid) {
            n = (u8)sprintf(p, " %s:---.- ", tickers[i].symbol);
            for (j = 0; j < n; j++) pp[j] = PAL0;
            p += n; pp += n;
            continue;
        }
        {
            s32 price  = tickers[i].price_cents;
            s32 pc     = tickers[i].prev_close_cents;
            s32 delta  = price - pc;
            char sign  = (delta >= 0) ? '+' : '-';
            s32 adelta = (delta < 0) ? -delta : delta;
            u8  pal    = (delta >= 0) ? PAL1 : PAL2; /* green / red */

            n = (u8)sprintf(p, " %s:$%ld.%02ld(%c%ld.%02ld) ",
                         tickers[i].symbol,
                         (long)(price / 100),  (long)(price % 100),
                         sign,
                         (long)(adelta / 100), (long)(adelta % 100));
            /* " SYMBOL:" portion = white; price/delta portion = green/red */
            for (j = 0; j < white_len && j < n; j++) pp[j] = PAL0;
            for (      ; j < n;                 j++) pp[j] = pal;
            p += n; pp += n;
        }
    }
    *p  = '\0';
    *pp = PAL0;
    marquee_pending = true;
}

/* -------------------------------------------------------------------------
 * init_nasdaq_bg()  [compiled only when BCKGND_ON is defined]
 * Loads money-tile background into BG_B with diagonal scroll.
 * To enable: make BCKGND_ON=1  (or -DBCKGND_ON in CFLAGS)
 * ---------------------------------------------------------------------- */
#ifdef BCKGND_ON
/* Solid-black masking tile for BG_A text rows (all pixels = PAL0 index 1). */
#define BLACK_TILE_IDX  (TILE_FONT_INDEX - 1)
static const u32 black_tile_data[8] = {
    0x11111111, 0x11111111, 0x11111111, 0x11111111,
    0x11111111, 0x11111111, 0x11111111, 0x11111111
};

static void init_nasdaq_bg(void)
{
    u16 col, row;
    u16 i;
    PAL_setColors(PAL3 * 16, nasdaq_bg.palette->data, 15, CPU);
    PAL_setColor(63, RGB24_TO_VDPCOLOR(0x00AAFF));

    VDP_loadTileSet(nasdaq_bg.tileset, TILE_USER_INDEX, DMA);
    VDP_waitDMACompletion();

    /* Mask only text rows on BG_A; open rows remain transparent (show BG_B). */
    {
        u16 black = TILE_ATTR_FULL(PAL0, FALSE, FALSE, FALSE, BLACK_TILE_IDX);
        u16 r;
        VDP_loadTileData(black_tile_data, BLACK_TILE_IDX, 1, CPU);
        VDP_fillTileMapRect(BG_A, black, 0, 0, 40, 4);
        for (r = 0; r < MAX_TICKERS; r++)
            VDP_fillTileMapRect(BG_A, black, 0,
                                PRICE_START_ROW + r * PRICE_ROW_STRIDE, 40, 1);
    }

    /* Tile BG_B (64×32) with the 16×8 pattern (64÷16=4, 32÷8=4 — seamless). */
    for (row = 0; row < 32; row++) {
        for (col = 0; col < 64; col++) {
            u16 src      = (u16)((row % 8) * 16 + (col % 16));
            u16 tile_idx = nasdaq_bg.tilemap->tilemap[src];
            u16 attr     = TILE_ATTR_FULL(PAL3, FALSE, FALSE, FALSE,
                                          TILE_USER_INDEX + tile_idx);
            VDP_setTileMapXY(BG_B, attr, col, row);
        }
    }

    for (i = 0; i < 32; i++) bgb_hscroll[i] = 0;
    VDP_setHorizontalScrollTile(BG_B, 0, bgb_hscroll, 32, DMA);
    { s16 zero = 0; VDP_setHorizontalScrollTile(BG_A, 0, &zero, 1, CPU); }
    VDP_setVerticalScroll(BG_B, 0);
}
#endif /* BCKGND_ON */

/* -------------------------------------------------------------------------
 * write_marquee_tiles() — rewrites BG_B tilemap from current marquee buffer.
 * Called only when content changes (new fetch), NOT every frame.
 * The scroll effect is produced entirely by the scroll register.
 * ---------------------------------------------------------------------- */
static void write_marquee_tiles(void)
{
    const char *buf    = marquee_buf[marquee_read_idx];
    const u8   *palbuf = marquee_pal_buf[marquee_read_idx];
    u16 slen = (u16)strlen(buf);
    u16 col;

    if (!slen) return;

    for (col = 0; col < 64; col++) {
        u16 src      = col % slen;
        u8  ch       = (u8)buf[src];
        u8  pal      = palbuf[src];
        u16 tile_idx = (ch >= 0x20 && ch <= 0x7E)
                     ? (TILE_FONT_INDEX + (ch - 0x20))
                     : TILE_FONT_INDEX;
        VDP_setTileMapXY(BG_A,
            TILE_ATTR_FULL(pal, FALSE, FALSE, FALSE, tile_idx),
            col, MARQUEE_ROW);
    }
}

/* -------------------------------------------------------------------------
 * update_marquee_scroll() — must be first call after VDP_waitVSync so the
 * scroll register write lands in VBlank before active display begins.
 * Rewrites tilemap only when new content is pending (infrequent).
 * ---------------------------------------------------------------------- */
static void update_marquee_scroll(void)
{
    s16 neg_scroll;
    u16 i;

    if (marquee_pending) {
        marquee_read_idx = 1 - marquee_read_idx;
        marquee_pending  = false;
        write_marquee_tiles(); /* now writes to BG_A row 27 */
    }

    /* --- Marquee: BG_A row 27 scrolls independently (HSCROLL_TILE) --- */
    scroll_x  = (scroll_x + TICKER_SCROLL_SPEED) & 0x1FF;
    neg_scroll = -(s16)scroll_x;
    VDP_setHorizontalScrollTile(BG_A, MARQUEE_ROW, &neg_scroll, 1, CPU);

#ifdef BCKGND_ON
    /* --- NASDAQ background: BG_B diagonal scroll (+1X +1Y per frame) --- */
    bg_sx = (s16)((bg_sx + 1) & 0x1FF);
    bg_sy = (s16)((bg_sy + 1) & 0xFF);

    neg_scroll = -(s16)bg_sx;
    for (i = 0; i < 32; i++) bgb_hscroll[i] = neg_scroll;
    VDP_setHorizontalScrollTile(BG_B, 0, bgb_hscroll, 32, DMA);
    VDP_setVerticalScroll(BG_B, (s16)bg_sy);
#endif
}

/* -------------------------------------------------------------------------
 * draw_price_panel()
 * ---------------------------------------------------------------------- */
/* draw_price_panel()
 * Layout (40-char screen, all columns 0-based):
 *   col  1- 5  symbol (company color)
 *   col  6-15  price  "$%-4ld.%02ld  " = 10 chars fixed (white)
 *   col 16-29  delta  " %c%ld.%02ld(%c%ld.%02ld%%)" padded to 14 (green/red)
 *   col 30-37  time   "HH:MM xM"  8 chars (white)
 *
 * No row-clear: each field is padded to a fixed width so it always
 * overwrites any stale characters from a previous shorter value.
 * Called immediately after VDP_waitVSync() for tear-free rendering.
 */
/* Draw a single ticker row — called once per frame (rolling) to avoid stutter. */
static void draw_price_row(u8 i)
{
    char pricebuf[16];
    char deltabuf[20];
    u8   n;
    u8   row = PRICE_START_ROW + i * PRICE_ROW_STRIDE;

    /* symbol: company logo color (GOOGL gets per-letter treatment) */
    if (i == 5 /* GOOGL */) {
        draw_googl_symbol(1, row);
    } else {
        VDP_setTextPalette(ticker_sym_pal[i]);
        VDP_drawText(tickers[i].symbol, 1, row);
    }

    if (!tickers[i].valid) {
        VDP_setTextPalette(PAL0);
        VDP_drawText("  Loading...              ", 6, row);
        return;
    }

    {
        s32 price  = tickers[i].price_cents;
        s32 pc     = tickers[i].prev_close_cents;
        s32 delta  = price - pc;
        char sign  = (delta >= 0) ? '+' : '-';
        s32 adelta = (delta < 0) ? -delta : delta;
        s32 pct    = pc ? (adelta * 10000L / pc) : 0;

        /* price — 10 chars fixed */
        n = (u8)sprintf(pricebuf, "$%ld.%02ld",
                        (long)(price / 100), (long)(price % 100));
        while (n < 10) pricebuf[n++] = ' ';
        pricebuf[10] = '\0';
        VDP_setTextPalette(PAL0);
        VDP_drawText(pricebuf, 6, row);

        /* delta — 14 chars fixed (green/red) */
        n = (u8)sprintf(deltabuf, " %c%ld.%02ld(%c%ld.%02ld%%)",
                        sign, (long)(adelta / 100), (long)(adelta % 100),
                        sign, (long)(pct / 100),    (long)(pct % 100));
        while (n < 14) deltabuf[n++] = ' ';
        deltabuf[14] = '\0';
        if (delta < 0)
            VDP_setTextPalette(PAL2); /* red   — loss */
        else
            VDP_setTextPalette(PAL1); /* green — gain */
        VDP_drawText(deltabuf, 16, row);

        /* timestamp — 8 chars (white) */
        VDP_setTextPalette(PAL0);
        VDP_drawText(tickers[i].timestamp, 30, row);
    }
}

static void draw_price_panel(void)
{
    u8 i;
    for (i = 0; i < MAX_TICKERS; i++)
        draw_price_row(i);
}

/* -------------------------------------------------------------------------
 * draw_title()
 * ---------------------------------------------------------------------- */
static void draw_title(void)
{
    char title[42];
    sprintf(title, "[ MegaWifi Stock Ticker v%d.%d %s ]",
            (int)fw_major, (int)fw_minor, fw_variant);
    VDP_setTextPalette(PAL0);
    VDP_drawText(title, 0, 0);
}

/* -------------------------------------------------------------------------
 * user_tsk()
 * ---------------------------------------------------------------------- */
static void user_tsk(void)
{
    while (1) mw_process();
}

/* -------------------------------------------------------------------------
 * megawifi_init()
 * ---------------------------------------------------------------------- */
static bool megawifi_init(void)
{
    char *variant = NULL;
    struct mw_ip_cfg dhcp_cfg = { {0}, {0}, {0}, {0}, {0} };
    enum mw_err err;

    if (mw_init(cmd_buf, MW_BUFLEN) != MW_ERR_NONE) return false;
    TSK_userSet(user_tsk);

    err = mw_detect(&fw_major, &fw_minor, &variant);
    if (err != MW_ERR_NONE) return false;
    if (variant) {
        uint8_t i;
        for (i = 0; i < sizeof(fw_variant_buf) - 1 && variant[i]; i++)
            fw_variant_buf[i] = variant[i];
        fw_variant_buf[i] = '\0';
    }

    err = mw_ap_cfg_set(AP_SLOT, AP_SSID, AP_PASS, MW_PHY_11BGN);
    if (err != MW_ERR_NONE) return false;

    err = mw_ip_cfg_set(AP_SLOT, &dhcp_cfg);
    if (err != MW_ERR_NONE) return false;

    err = mw_cfg_save();
    if (err != MW_ERR_NONE) return false;

    err = mw_ap_assoc(AP_SLOT);
    if (err != MW_ERR_NONE) return false;

    err = mw_ap_assoc_wait(30 * FPS);
    if (err != MW_ERR_NONE) return false;

    mw_sleep(3 * 60); /* stabilisation — critical */

    {
        const char *ntp[3] = { "0.pool.ntp.org", "1.pool.ntp.org", "2.pool.ntp.org" };
        mw_sntp_cfg_set("CST6CDT", ntp); /* US Central, auto DST */
    }

    return true;
}

/* -------------------------------------------------------------------------
 * main()
 * ---------------------------------------------------------------------- */
int main(bool hard_reset)
{
    u16 frame        = UPDATE_FRAMES;
    u8  ticker_cycle = 0;

    /* --- VDP setup ---------------------------------------------------- */
    VDP_setScreenWidth320();
    VDP_setPlaneSize(64, 32, TRUE);
    /* HSCROLL_TILE: each 8-scanline tile row has its own H-scroll value.
     * BG_A rows 0-26 = 0 (static text), BG_A row 27 = marquee scroll.
     * BG_B all rows = -bg_sx (diagonal logo background). */
    VDP_setScrollingMode(HSCROLL_TILE, VSCROLL_PLANE);
    VDP_clearPlane(BG_A, TRUE);
    VDP_clearPlane(BG_B, TRUE);

    /* --- Palette setup ------------------------------------------------
     * SGDK font tiles use pixel value 0xF (15) as the foreground colour.
     * The foreground slot is therefore colour index 15 within each palette:
     *   PAL0 = global CRAM[15], PAL1 = CRAM[31], PAL2 = CRAM[47], PAL3 = CRAM[63]
     * CRAM[0] sets the VDP screen background colour.
     * All other palette bg entries default to 0 (black) on hardware reset.
     * ------------------------------------------------------------------ */
    PAL_setColor(0,  RGB24_TO_VDPCOLOR(0x000000)); /* VDP background = black */
    PAL_setColor(15, RGB24_TO_VDPCOLOR(0xFFFFFF)); /* PAL0: white  — prices, neutral text */
    PAL_setColor(31, RGB24_TO_VDPCOLOR(0x00CC00)); /* PAL1: green  — gains  / NVDA        */
    PAL_setColor(47, RGB24_TO_VDPCOLOR(0xFF2020)); /* PAL2: red    — losses / ORCL         */
    PAL_setColor(63, RGB24_TO_VDPCOLOR(0x00AAFF)); /* PAL3: cyan   — IBM / MSFT / GOOGL G  */
    VDP_waitVSync(); /* flush CRAM writes before first draw */

    /* --- NASDAQ tiled background (enable with -DBCKGND_ON) ------------ */
#ifdef BCKGND_ON
    init_nasdaq_bg();
#endif

    /* --- Initial title ------------------------------------------------ */
    VDP_setTextPalette(PAL0);
    VDP_drawText("[ MegaWifi Stock Ticker ]", 0, 0);

    /* --- WiFi init ---------------------------------------------------- */
    status_info("Connecting to WiFi...");
    if (!megawifi_init()) {
        status_err("WiFi init FAILED — halted");
        while (1) VDP_waitVSync();
    }

    draw_title(); /* update title with real fw version */
    status_info("WiFi OK — waiting for NTP...");

    /* --- NTP sync ----------------------------------------------------- */
    {
        int frames = 0;
        int max_frames = MS_TO_FRAMES(15000);
        char nbuf[42];
        while (frames < max_frames) {
            union mw_msg_sys_stat *ss = mw_sys_stat_get();
            if (ss && ss->dt_ok) break;
            VDP_waitVSync();
            frames++;
        }
        if (frames >= max_frames) {
            sprintf(nbuf, "NTP timeout (%ds) — continuing", (int)(frames / 60));
            status_err(nbuf);
        } else {
            status_clear();
        }
    }

    mw_http_cleanup(); /* pre-fetch cleanup */

    /* --- Initial fetch ------------------------------------------------ */
    {
        u8 i;
        for (i = 0; i < MAX_TICKERS; i++)
            fetch_quote(i);
        rebuild_marquee();
        draw_price_panel();
    }

    draw_countdown(0);

    /* --- Main loop ---------------------------------------------------- */
    while (1) {
        VDP_waitVSync();

        /* Scroll update MUST be first — scroll register write must land in
         * VBlank before the VDP starts rendering, otherwise the top pixels
         * of the marquee font glitch (VDP reads stale HSCROLL mid-render). */
        update_marquee_scroll();

        /* Draw one ticker row per frame (rolling) — spreads VRAM writes,
         * eliminates the 32-frame stutter from writing all 6 rows at once. */
        draw_price_row(frame % MAX_TICKERS);

        if ((frame % FPS) == 0)
            draw_countdown(frame);

        frame++;
        if (frame >= UPDATE_FRAMES) {
            frame = 0;
            fetch_quote(ticker_cycle);
            rebuild_marquee();
            ticker_cycle = (ticker_cycle + 1) % MAX_TICKERS;
            draw_countdown(frame);
        }
    }

    return 0;
}
