/*
 * stock_ticker.c
 * Sega Genesis stock ticker using SGDK + MegaWiFi ESP32-C3
 *
 * Displays scrolling ticker tape on plane B, static prices on plane A.
 * Polls Finnhub /quote endpoint over HTTPS every ~10 seconds (round-robin).
 *
 * Build: SGDK with mw-api linked in. Set MW_BUFLEN to at least 512.
 *
 * HTTPS: TLS handled by the firmware's built-in Mozilla CA bundle
 * (CONFIG_MBEDTLS_CERTIFICATE_BUNDLE=y). No custom cert upload needed.
 */

#include <genesis.h>
#include <task.h>
#include <string.h>
#include "ext/mw/megawifi.h"
#include "ext/mw/mw-msg.h"
#include "nasdaq_bg.h"   /* generated by rescomp from res/nasdaq_bg.res */
#include "ticker_search.h"

/* Declared in our local src/megawifi.c — keeps display live during fetches */
extern void mw_set_draw_hook(void (*hook)(void));

/* Forward declarations for fetch_draw_hook */
static void update_marquee_scroll(void);
static void draw_price_row(u8 i);

#ifndef MW_MS_TO_FRAMES
#define MW_MS_TO_FRAMES(ms) (((ms) * 60 + 999) / 1000) /* ms -> 60Hz frames */
#endif
/* no stdlib.h available in SGDK headers; provide minimal prototypes */
long atol(const char *nptr);

/* 64-bit integer type — not in SGDK's types.h but available from GCC */
typedef signed long long   s64;
typedef unsigned long long u64;

static char *find_char(const char *s, char c)
{
    while (*s) { if (*s == c) return (char*)s; s++; }
    return NULL;
}

static const char *find_substr(const char *hay, const char *needle)
{
    if (!*needle) return hay;
    while (*hay) {
        const char *h = hay;
        const char *n = needle;
        while (*h && *n && (*h == *n)) { h++; n++; }
        if (*n == '\0') return hay;
        hay++;
    }
    return NULL;
}

/* -------------------------------------------------------------------------
 * Config
 * ---------------------------------------------------------------------- */
#define MS_TO_FRAMES(ms)    ((((ms) * 60 / 500) + 1) / 2)
#define FPS                 60
#define AP_SLOT             0
#define AP_SSID             "YourSSID"
#define AP_PASS             "YourPassword"
/* 10s per ticker × 8 tickers = 80s full cycle = 6 calls/min (limit: 60/min) */
#define UPDATE_FRAMES       (FPS * 10)
#define MAX_TICKERS         8
#define TICKER_SCROLL_SPEED 1
#define COPYRIGHT_ROW       2               /* copyright line (blank row 1 above) */
#define COPYRIGHT_COL       2               /* aligned with "M" in MegaWifi  */
#define COUNTDOWN_ROW       4               /* "Next Update: Xs" (blank row 3 above) */
#define COUNTDOWN_COL       2              /* under "M" in MegaWifi         */
#define STATUS_ROW          5               /* error-only status line        */
/* Prices centered between STATUS_ROW+1 and MARQUEE_ROW-1 */
#define PRICE_START_ROW     7
#define PRICE_ROW_STRIDE    2
/* Net worth line: one blank row after the last ticker */
#define NET_WORTH_ROW       (PRICE_START_ROW + MAX_TICKERS * PRICE_ROW_STRIDE + 1)
#define MARQUEE_ROW         27              /* bottom row of the screen      */
#ifndef FINNHUB_TOKEN
#define FINNHUB_TOKEN   "REPLACE_WITH_YOUR_TOKEN"
#warning "FINNHUB_TOKEN not defined; using placeholder will fail authentication"
#endif
#define FINNHUB_URL_FMT "https://finnhub.io/api/v1/quote?symbol=%s&token=%s"

/* -------------------------------------------------------------------------
 * Ticker data
 * ---------------------------------------------------------------------- */
typedef struct {
    char        symbol[8];          /* mutable — all slots editable          */
    s32         price_cents;
    s32         prev_close_cents;
    bool        valid;
    char        timestamp[12];      /* "HH:MM AM\0" (CST)                    */
    u32         shares_owned;       /* number of shares held                 */
} TickerEntry;

/* Default symbols for all 8 slots — all editable at runtime. */
static const char *default_syms[MAX_TICKERS] = {
    "ORCL", "NVDA", "AMZN", "IBM", "MSFT", "GOOGL", "META", "AVGO"
};

static TickerEntry tickers[MAX_TICKERS];

/* Per-ticker symbol palette — matched to corporate logo colours.
 * Four working palettes (all use foreground slot index 15 within palette):
 *   PAL0 = white   PAL1 = green   PAL2 = red   PAL3 = cyan
 *
 * GOOGL gets per-letter multi-colour treatment (see draw_googl_symbol).
 * Slots with no recognised symbol default to PAL0. */
static u8 ticker_sym_pal[MAX_TICKERS] = {
    PAL2, /* ORCL  — Oracle red          */
    PAL1, /* NVDA  — Nvidia green        */
    PAL0, /* AMZN  — white (no orange)   */
    PAL3, /* IBM   — IBM blue/cyan       */
    PAL3, /* MSFT  — Microsoft cyan      */
    PAL0, /* GOOGL — multi (see below)   */
    PAL1, /* META  — Meta green          */
    PAL0, /* AVGO  — white               */
};

/* Update the palette for a slot when its symbol changes. */
static void update_ticker_pal(u8 i)
{
    const char *s = tickers[i].symbol;
    u8 pal = PAL0;
    if      (s[0]=='O' && s[1]=='R' && s[2]=='C' && s[3]=='L' && !s[4]) pal = PAL2;
    else if (s[0]=='N' && s[1]=='V' && s[2]=='D' && s[3]=='A' && !s[4]) pal = PAL1;
    else if (s[0]=='I' && s[1]=='B' && s[2]=='M' && !s[3])              pal = PAL3;
    else if (s[0]=='M' && s[1]=='S' && s[2]=='F' && s[3]=='T' && !s[4]) pal = PAL3;
    else if (s[0]=='M' && s[1]=='E' && s[2]=='T' && s[3]=='A' && !s[4]) pal = PAL1;
    else if (s[0]=='G' && s[1]=='O' && s[2]=='O' && s[3]=='G' && s[4]=='L' && !s[5]) pal = PAL0; /* multi */
    ticker_sym_pal[i] = pal;
}

/* draw_googl_symbol() — renders "GOOGL" letter-by-letter in Google brand colours.
 *   G=cyan(PAL3)  O=red(PAL2)  O=white(PAL0)  G=cyan(PAL3)  L=green(PAL1) */
static void draw_googl_symbol(u8 col, u8 row)
{
    static const char letters[] = "GOOGL";
    static const u8   pals[]    = { PAL3, PAL2, PAL0, PAL3, PAL1 };
    char ch[2] = { 0, 0 };
    u8 i;
    for (i = 0; i < 5; i++) {
        ch[0] = letters[i];
        VDP_setTextPalette(pals[i]);
        VDP_drawText(ch, col + i, row);
    }
}

static bool is_googl(u8 i)
{
    const char *s = tickers[i].symbol;
    return s[0]=='G' && s[1]=='O' && s[2]=='O' && s[3]=='G' && s[4]=='L' && !s[5];
}

/* -------------------------------------------------------------------------
 * RNG seed counter — incremented in draw hook (fires every VBlank during
 * all mw_command waits, including WiFi association and mw_sleep).
 * Seeded into SGDK's setRandomSeed() after WiFi + NTP init.
 * ---------------------------------------------------------------------- */
static u16 rng_seed_ctr = 0;

/* -------------------------------------------------------------------------
 * Selection / share-edit state
 *   selected  : which ticker row the cursor is on (-1 = none)
 *   editing   : TRUE = UP/DOWN/LEFT/RIGHT/A/B modify share count
 * ---------------------------------------------------------------------- */
static s8  selected  = -1;
static bool editing  = false;

/* -------------------------------------------------------------------------
 * Scrolling marquee state
 * ---------------------------------------------------------------------- */
static char  marquee_buf[2][256];
static u8    marquee_pal_buf[2][256];   /* palette per character */
static u8    marquee_read_idx = 0;
static volatile bool marquee_pending = false;
static u16   scroll_x = 0;
/* Streaming position: index (before % slen) of the next char to write into
 * the tilemap.  Reset to 64 each time content changes (initial fill = 0..63). */
static u16   marquee_str_pos = 0;

/* -------------------------------------------------------------------------
 * NASDAQ diagonal background scroll state
 * HSCROLL_TILE mode: bgb_hscroll[] holds -bg_sx for every tile row of BG_B.
 * BG_A rows 0-26 stay at 0; BG_A row 27 (marquee) scrolls independently.
 * ---------------------------------------------------------------------- */
#ifdef BCKGND_ON
static s16 bg_sx = 0;
static s16 bg_sy = 0;
static s16 bgb_hscroll[32];  /* uniform horizontal scroll for all BG_B tile rows */
#endif

/* -------------------------------------------------------------------------
 * MegaWiFi shared command buffer
 * ---------------------------------------------------------------------- */
static uint16_t cmd_buf[MW_BUFLEN/2];

/* Firmware version */
static uint8_t fw_major = 0, fw_minor = 0;
static char fw_variant_buf[32] = "?";
static char *fw_variant = fw_variant_buf;

/* Last-update timestamp shown on the countdown row: "mm/dd/yy H:MM:SS XM" */
static char last_update_str[24] = "";

/* Convert 3-letter month abbreviation to month number 1-12 (0 = unknown). */
static u8 month_from_abbr(const char *m)
{
    static const char mo[12][4] = {
        "Jan","Feb","Mar","Apr","May","Jun",
        "Jul","Aug","Sep","Oct","Nov","Dec"
    };
    u8 i;
    for (i = 0; i < 12; i++)
        if (m[0] == mo[i][0] && m[1] == mo[i][1] && m[2] == mo[i][2])
            return (u8)(i + 1);
    return 0;
}

/* -------------------------------------------------------------------------
 * status_clear() / status_err()
 * STATUS_ROW is blank during normal operation; red text on error.
 * ---------------------------------------------------------------------- */
static void status_clear(void)
{
    VDP_setTextPalette(PAL0);
    VDP_drawText("                                        ", 0, STATUS_ROW);
}

static void status_err(const char *msg)
{
    char buf[42];
    uint8_t i = 0;
    while (msg[i] && i < 39) { buf[i] = msg[i]; i++; }
    while (i < 40) buf[i++] = ' ';
    buf[40] = '\0';
    VDP_setTextPalette(PAL2); /* red */
    VDP_drawText(buf, 0, STATUS_ROW);
    VDP_setTextPalette(PAL0);
    VDP_waitVSync();
}

/* Used only during init for one-time progress messages */
static void status_info(const char *msg)
{
    char buf[42];
    uint8_t i = 0;
    while (msg[i] && i < 39) { buf[i] = msg[i]; i++; }
    while (i < 40) buf[i++] = ' ';
    buf[40] = '\0';
    VDP_setTextPalette(PAL0);
    VDP_drawText(buf, 0, STATUS_ROW);
    VDP_waitVSync();
}

/* -------------------------------------------------------------------------
 * draw_countdown() — row COUNTDOWN_ROW, col COUNTDOWN_COL, white (PAL0)
 * ---------------------------------------------------------------------- */
static void draw_countdown(u16 frame)
{
    int secs = (int)((UPDATE_FRAMES - frame) / FPS);
    char buf[42];
    if (last_update_str[0])
        sprintf(buf, "Next Update:%2ds %s  ", secs, last_update_str);
    else
        sprintf(buf, "Next Update: %2ds                    ", secs);
    VDP_setTextPalette(PAL0); /* white */
    VDP_drawText(buf, COUNTDOWN_COL, COUNTDOWN_ROW);
}

/* -------------------------------------------------------------------------
 * Minimal JSON number parser
 * ---------------------------------------------------------------------- */
static s32 parse_json_price_cents(const char *body, const char *key)
{
    const char *p = find_substr(body, key);
    if (!p) return 0x7FFFFFFF;
    p = find_char(p, ':');
    if (!p) return 0x7FFFFFFF;
    p++;
    while (*p == ' ') p++;
    int sign = 1;
    if (*p == '-') { sign = -1; p++; }
    long ipart = 0;
    while (*p >= '0' && *p <= '9') { ipart = ipart * 10 + (*p - '0'); p++; }
    long frac = 0; int fdig = 0;
    if (*p == '.') {
        p++;
        while (*p >= '0' && *p <= '9' && fdig < 2) { frac = frac * 10 + (*p - '0'); fdig++; p++; }
        while (*p >= '0' && *p <= '9') p++;
    }
    if (fdig == 1) frac *= 10;
    return sign * (s32)(ipart * 100 + frac);
}

/* -------------------------------------------------------------------------
 * fetch_quote_https()
 * Status line is silent on success; shows error in red on failure.
 * ---------------------------------------------------------------------- */
static void fetch_quote_https(u8 idx)
{
    uint8_t ch = MW_HTTP_CH;
    int16_t cr = 0, ue = 0, me = 0, oe = 0, re = 0;
    int16_t http_status = 0;
    int16_t recv_len = 0;
    uint32_t content_len = 0;
    char url[160];
    char dbg[42];
    s32 price = 0x7FFFFFFF, prev = 0x7FFFFFFF;
    const char *sym = tickers[idx].symbol;

    cr = mw_http_cleanup();

    sprintf(url, FINNHUB_URL_FMT, sym, FINNHUB_TOKEN);
    ue = mw_http_url_set(url);
    if (ue) goto done;

    me = mw_http_method_set(MW_HTTP_METHOD_GET);
    if (me) goto done;

    mw_http_header_add("Accept", "application/json");

    oe = mw_http_open(0);
    if (oe) goto done;

    http_status = mw_http_finish(&content_len, MS_TO_FRAMES(12000));
    if (http_status < 200 || http_status >= 300 || content_len == 0) {
        mw_http_cleanup();
        goto done;
    }

    recv_len = (content_len < (uint32_t)(MW_BUFLEN - 2))
             ? (int16_t)content_len : (int16_t)(MW_BUFLEN - 2);
    re = mw_recv_sync(&ch, (char*)cmd_buf, &recv_len, MS_TO_FRAMES(12000));
    /* Parse BEFORE cleanup — cleanup reuses cmd_buf */
    if (!re && recv_len > 0) {
        ((char*)cmd_buf)[recv_len] = '\0';
        price = parse_json_price_cents((char*)cmd_buf, "\"c\"");
        prev  = parse_json_price_cents((char*)cmd_buf, "\"pc\"");
    }
    mw_http_cleanup();

done:
    {
        bool ok = (ue == 0 && me == 0 && oe == 0 &&
                   http_status >= 200 && http_status < 300 &&
                   re == 0 && recv_len > 0 &&
                   price != 0x7FFFFFFF && prev != 0x7FFFFFFF);
        if (ok) {
            status_clear();
        } else {
            sprintf(dbg, "[%-5s] c=%d u=%d m=%d o=%d f=%d r=%d",
                    sym, (int)cr, (int)ue, (int)me, (int)oe,
                    (int)http_status, (int)re);
            status_err(dbg);
        }
    }

    if (ue || me || oe || re || recv_len <= 0 ||
        price == 0x7FFFFFFF || prev == 0x7FFFFFFF ||
        http_status < 200 || http_status >= 300)
        return;

    tickers[idx].price_cents      = price;
    tickers[idx].prev_close_cents = prev;
    tickers[idx].valid            = true;
    /* Stamp the CST time this quote arrived; also update last_update_str */
    {
        uint32_t dt[2] = {0, 0};
        char *ts = mw_date_time_get(dt);
        /* ts: "WWW MMM DD HH:MM:SS YYYY" (ctime format, 24 chars + NUL) */
        if (ts && ts[11] && ts[16]) {
            uint8_t hh = (uint8_t)((ts[11]-'0')*10 + (ts[12]-'0'));
            const char *ampm = (hh >= 12) ? "PM" : "AM";
            if (hh == 0) hh = 12;
            else if (hh > 12) hh -= 12;
            /* "HH:MM AM\0" = 9 bytes, fits in timestamp[12] */
            sprintf(tickers[idx].timestamp, "%2d:%c%c %s",
                    (int)hh, ts[14], ts[15], ampm);
            /* Full date+time for countdown row: "mm/dd/yy H:MM:SS XM" */
            {
                u8 mon = month_from_abbr(&ts[4]);
                u8 day = (u8)((ts[8] == ' ' ? 0 : (ts[8]-'0')*10) + (ts[9]-'0'));
                u8 yr  = (u8)((ts[22]-'0')*10 + (ts[23]-'0'));
                u8 mm2 = (u8)((ts[14]-'0')*10 + (ts[15]-'0'));
                u8 ss  = (u8)((ts[17]-'0')*10 + (ts[18]-'0'));
                sprintf(last_update_str, "%02d/%02d/%02d %d:%02d:%02d %s",
                        (int)mon, (int)day, (int)yr,
                        (int)hh, (int)mm2, (int)ss, ampm);
            }
        }
    }
}

static void fetch_quote(u8 idx)
{
    if (tickers[idx].symbol[0] == '\0') return;
    fetch_quote_https(idx);
}

/* -------------------------------------------------------------------------
 * rebuild_marquee()
 * ---------------------------------------------------------------------- */
static void rebuild_marquee(void)
{
    u8    write_idx = 1 - marquee_read_idx;
    char *p   = marquee_buf[write_idx];
    u8   *pp  = marquee_pal_buf[write_idx];
    u8 i, j, n, sym_len, white_len;

    for (i = 0; i < MAX_TICKERS; i++) {
        if (tickers[i].symbol[0] == '\0') continue;
        sym_len   = (u8)strlen(tickers[i].symbol);
        white_len = 1 + sym_len + 1; /* leading space + symbol + ':' */

        if (!tickers[i].valid) {
            n = (u8)sprintf(p, " %s:---.- ", tickers[i].symbol);
            for (j = 0; j < n; j++) pp[j] = PAL0;
            p += n; pp += n;
            continue;
        }
        {
            s32 price  = tickers[i].price_cents;
            s32 pc     = tickers[i].prev_close_cents;
            s32 delta  = price - pc;
            char sign  = (delta >= 0) ? '+' : '-';
            s32 adelta = (delta < 0) ? -delta : delta;
            u8  pal    = (delta >= 0) ? PAL1 : PAL2; /* green / red */

            n = (u8)sprintf(p, " %s:$%ld.%02ld(%c%ld.%02ld) ",
                         tickers[i].symbol,
                         (long)(price / 100),  (long)(price % 100),
                         sign,
                         (long)(adelta / 100), (long)(adelta % 100));
            /* " SYMBOL:" portion = white; price/delta portion = green/red */
            for (j = 0; j < white_len && j < n; j++) pp[j] = PAL0;
            for (      ; j < n;                 j++) pp[j] = pal;
            p += n; pp += n;
        }
    }
    *p  = '\0';
    *pp = PAL0;
    marquee_pending = true;
}

/* -------------------------------------------------------------------------
 * init_nasdaq_bg()  [compiled only when BCKGND_ON is defined]
 * Loads money-tile background into BG_B with diagonal scroll.
 * To enable: make BCKGND_ON=1  (or -DBCKGND_ON in CFLAGS)
 * ---------------------------------------------------------------------- */
#ifdef BCKGND_ON
/* Solid-black masking tile for BG_A text rows (all pixels = PAL0 index 1). */
#define BLACK_TILE_IDX  (TILE_FONT_INDEX - 1)
static const u32 black_tile_data[8] = {
    0x11111111, 0x11111111, 0x11111111, 0x11111111,
    0x11111111, 0x11111111, 0x11111111, 0x11111111
};

static void init_nasdaq_bg(void)
{
    u16 col, row;
    u16 i;
    PAL_setColors(PAL3 * 16, nasdaq_bg.palette->data, 15, CPU);
    PAL_setColor(63, RGB24_TO_VDPCOLOR(0x00AAFF));

    VDP_loadTileSet(nasdaq_bg.tileset, TILE_USER_INDEX, DMA);
    VDP_waitDMACompletion();

    /* Mask text rows + net worth row on BG_A; open rows show BG_B. */
    {
        u16 black = TILE_ATTR_FULL(PAL0, FALSE, FALSE, FALSE, BLACK_TILE_IDX);
        u16 r;
        VDP_loadTileData(black_tile_data, BLACK_TILE_IDX, 1, CPU);
        VDP_fillTileMapRect(BG_A, black, 0, 0, 40, PRICE_START_ROW);
        for (r = 0; r < MAX_TICKERS; r++)
            VDP_fillTileMapRect(BG_A, black, 0,
                                PRICE_START_ROW + r * PRICE_ROW_STRIDE, 40, 1);
        VDP_fillTileMapRect(BG_A, black, 0, NET_WORTH_ROW, 40, 1);
    }

    /* Tile BG_B (64×32) with the 16×8 pattern (64÷16=4, 32÷8=4 — seamless). */
    for (row = 0; row < 32; row++) {
        for (col = 0; col < 64; col++) {
            u16 src      = (u16)((row % 8) * 16 + (col % 16));
            u16 tile_idx = nasdaq_bg.tilemap->tilemap[src];
            u16 attr     = TILE_ATTR_FULL(PAL3, FALSE, FALSE, FALSE,
                                          TILE_USER_INDEX + tile_idx);
            VDP_setTileMapXY(BG_B, attr, col, row);
        }
    }

    for (i = 0; i < 32; i++) bgb_hscroll[i] = 0;
    VDP_setHorizontalScrollTile(BG_B, 0, bgb_hscroll, 32, DMA);
    { s16 zero = 0; VDP_setHorizontalScrollTile(BG_A, 0, &zero, 1, CPU); }
    VDP_setVerticalScroll(BG_B, 0);
}
#endif /* BCKGND_ON */

/* -------------------------------------------------------------------------
 * write_marquee_stream_tile() — write one character into the tilemap.
 * tile_col : column in the 64-wide BG_A plane (0..63)
 * str_pos  : index into the current marquee string (before % slen)
 * ---------------------------------------------------------------------- */
static void write_marquee_stream_tile(u16 tile_col, u16 str_pos)
{
    const char *buf    = marquee_buf[marquee_read_idx];
    const u8   *palbuf = marquee_pal_buf[marquee_read_idx];
    u16 slen = (u16)strlen(buf);
    u8  ch, pal;
    u16 tile_idx;

    if (!slen) return;
    ch       = (u8)buf[str_pos % slen];
    pal      = palbuf[str_pos % slen];
    tile_idx = (ch >= 0x20 && ch <= 0x7E)
             ? (TILE_FONT_INDEX + (ch - 0x20))
             : TILE_FONT_INDEX;
    VDP_setTileMapXY(BG_A,
        TILE_ATTR_FULL(pal, FALSE, FALSE, FALSE, tile_idx),
        tile_col, MARQUEE_ROW);
}

/* -------------------------------------------------------------------------
 * update_marquee_scroll() — must be first call after VDP_waitVSync so the
 * scroll register write lands in VBlank before active display begins.
 * Rewrites tilemap only when new content is pending (infrequent).
 * ---------------------------------------------------------------------- */
static void update_marquee_scroll(void)
{
    s16 neg_scroll;
#ifdef BCKGND_ON
    u16 i;
#endif

    if (marquee_pending) {
        u16 c;
        marquee_read_idx = 1 - marquee_read_idx;
        marquee_pending  = false;
        /* Initial fill: starting from the current scroll position, write 64
         * chars into the 64-tile circular tilemap so the visible window is
         * immediately populated with fresh content (chars 0..63). */
        for (c = 0; c < 64; c++)
            write_marquee_stream_tile((u16)((scroll_x / 8 + c) % 64), c);
        marquee_str_pos = 64; /* next char to stream after the initial fill */
    }

    /* --- Marquee: BG_A row 27 scrolls independently (HSCROLL_TILE) --- */
    scroll_x  = (scroll_x + TICKER_SCROLL_SPEED) & 0x1FF;
    neg_scroll = -(s16)scroll_x;
    VDP_setHorizontalScrollTile(BG_A, MARQUEE_ROW, &neg_scroll, 1, CPU);

    /* Stream the next char each time the scroll crosses a tile boundary. */
    if ((scroll_x % 8) == 0) {
        u16 exited = (u16)((scroll_x / 8 + 63) % 64);
        write_marquee_stream_tile(exited, marquee_str_pos);
        marquee_str_pos++;
    }

#ifdef BCKGND_ON
    /* --- NASDAQ background: BG_B diagonal scroll (+1X +1Y per frame) --- */
    bg_sx = (s16)((bg_sx + 1) & 0x1FF);
    bg_sy = (s16)((bg_sy + 1) & 0xFF);

    neg_scroll = -(s16)bg_sx;
    for (i = 0; i < 32; i++) bgb_hscroll[i] = neg_scroll;
    VDP_setHorizontalScrollTile(BG_B, 0, bgb_hscroll, 32, DMA);
    VDP_setVerticalScroll(BG_B, (s16)bg_sy);
#endif
}

/* -------------------------------------------------------------------------
 * fetch_draw_hook() — called by mw_command() once per frame while waiting
 * for an ESP32 HTTP response.  Keeps the display alive during the ~0.5–1.5 s
 * round-trip that would otherwise freeze the screen.
 * Also increments rng_seed_ctr to accumulate entropy from WiFi init timing.
 * ---------------------------------------------------------------------- */
static void fetch_draw_hook(void)
{
    static u16 hook_frame = 0;
    rng_seed_ctr++;
    /* TSK_superPend(1) already consumed a VBlank before this hook fires —
     * do NOT call VDP_waitVSync() here (re-entrant into SGDK task system).
     * Skip tile draws when the search popup is covering the screen. */
    update_marquee_scroll();
    if (!ticker_search_active())
        draw_price_row((u8)(hook_frame % MAX_TICKERS));
    hook_frame++;
}

/* -------------------------------------------------------------------------
 * format_net_worth() — format s64 cents as "$NNN,NNN,NNN,NNN" whole dollars
 * (no cents displayed).  Handles up to 999 billion dollars.
 * ---------------------------------------------------------------------- */
static void format_net_worth(char *buf, s64 total_cents)
{
    s64 dollars;
    u32 bil, rem, mil, tho, hun;

    if (total_cents < 0) total_cents = 0;
    dollars = total_cents / (s64)100;

    bil = (u32)(dollars / (s64)1000000000);
    rem = (u32)(dollars % (s64)1000000000);
    mil = rem / 1000000;
    tho = (rem / 1000) % 1000;
    hun = rem % 1000;

    if (bil > 0)
        sprintf(buf, "$%lu,%03lu,%03lu,%03lu",
                (unsigned long)bil, (unsigned long)mil,
                (unsigned long)tho, (unsigned long)hun);
    else if (mil > 0)
        sprintf(buf, "$%lu,%03lu,%03lu",
                (unsigned long)mil, (unsigned long)tho, (unsigned long)hun);
    else if (tho > 0)
        sprintf(buf, "$%lu,%03lu",
                (unsigned long)tho, (unsigned long)hun);
    else
        sprintf(buf, "$%lu", (unsigned long)hun);
}

/* -------------------------------------------------------------------------
 * draw_net_worth() — NET_WORTH_ROW, white label + cyan value
 * ---------------------------------------------------------------------- */
static void draw_net_worth(void)
{
    s64  total_cents = 0;
    char amtbuf[20];
    char line[42];
    u8   i, used;

    for (i = 0; i < MAX_TICKERS; i++) {
        if (tickers[i].valid && tickers[i].shares_owned > 0)
            total_cents += (s64)tickers[i].price_cents * (s64)tickers[i].shares_owned;
    }

    format_net_worth(amtbuf, total_cents);

    /* "Net Worth: " = 11 chars, then value in cyan, then spaces to end of line */
    VDP_setTextPalette(PAL0);
    VDP_drawText("Net Worth: ", 0, NET_WORTH_ROW);
    VDP_setTextPalette(PAL3);
    VDP_drawText(amtbuf, 11, NET_WORTH_ROW);
    used = (u8)(11 + strlen(amtbuf));
    for (i = 0; i < (u8)(40 - used) && i < sizeof(line) - 1; i++) line[i] = ' ';
    line[i] = '\0';
    VDP_setTextPalette(PAL0);
    if (i > 0) VDP_drawText(line, used, NET_WORTH_ROW);
}

/* -------------------------------------------------------------------------
 * draw_price_panel()
 * ---------------------------------------------------------------------- */
/* draw_price_panel()
 * Layout (40-char screen, all columns 0-based):
 *   col  0      cursor '>' if selected, ' ' otherwise
 *   col  1- 5  symbol (company color)
 *   col  6-15  price  "$%-4ld.%02ld  " = 10 chars fixed (white)
 *   col 16-29  delta  " %c%ld.%02ld(%c%ld.%02ld%%)" padded to 14 (green/red)
 *   col 30-37  time   "HH:MM xM"  8 chars (white) — or share count when selected
 *
 * No row-clear: each field is padded to a fixed width so it always
 * overwrites any stale characters from a previous shorter value.
 */
/* Draw a single ticker row — called once per frame (rolling) to avoid stutter. */
static void draw_price_row(u8 i)
{
    char pricebuf[16];
    char deltabuf[20];
    char rightbuf[12]; /* timestamp or share count */
    u8   n;
    u8   row = PRICE_START_ROW + i * PRICE_ROW_STRIDE;
    bool sel = (selected == (s8)i);

    /* skip empty slots — clear the row */
    if (tickers[i].symbol[0] == '\0') {
        VDP_setTextPalette(PAL0);
        VDP_drawText("                                        ", 0, row);
        return;
    }

    /* cursor */
    VDP_setTextPalette(sel ? PAL1 : PAL0);
    VDP_drawText(sel ? ">" : " ", 0, row);

    /* symbol: company logo color (GOOGL gets per-letter treatment) */
    if (is_googl(i)) {
        draw_googl_symbol(1, row);
    } else {
        VDP_setTextPalette(ticker_sym_pal[i]);
        VDP_drawText(tickers[i].symbol, 1, row);
        /* pad to 5 chars */
        {
            u8 slen = (u8)strlen(tickers[i].symbol);
            if (slen < 5) {
                char pad[5] = "     ";
                pad[5 - slen] = '\0';
                VDP_setTextPalette(PAL0);
                VDP_drawText(pad, (u16)(1 + slen), row);
            }
        }
    }

    if (!tickers[i].valid) {
        VDP_setTextPalette(PAL0);
        VDP_drawText("  Loading...              ", 6, row);
        return;
    }

    {
        s32 price  = tickers[i].price_cents;
        s32 pc     = tickers[i].prev_close_cents;
        s32 delta  = price - pc;
        char sign  = (delta >= 0) ? '+' : '-';
        s32 adelta = (delta < 0) ? -delta : delta;
        s32 pct    = pc ? (adelta * 10000L / pc) : 0;

        /* price — 10 chars fixed */
        n = (u8)sprintf(pricebuf, "$%ld.%02ld",
                        (long)(price / 100), (long)(price % 100));
        while (n < 10) pricebuf[n++] = ' ';
        pricebuf[10] = '\0';
        VDP_setTextPalette(PAL0);
        VDP_drawText(pricebuf, 6, row);

        /* delta — 14 chars fixed (green/red) */
        n = (u8)sprintf(deltabuf, " %c%ld.%02ld(%c%ld.%02ld%%)",
                        sign, (long)(adelta / 100), (long)(adelta % 100),
                        sign, (long)(pct / 100),    (long)(pct % 100));
        while (n < 14) deltabuf[n++] = ' ';
        deltabuf[14] = '\0';
        if (delta < 0)
            VDP_setTextPalette(PAL2); /* red   — loss */
        else
            VDP_setTextPalette(PAL1); /* green — gain */
        VDP_drawText(deltabuf, 16, row);

        /* right column (col 30-39) — share count if selected, timestamp otherwise */
        if (sel) {
            /* show share count; blink brackets when editing */
            u32 sh = tickers[i].shares_owned;
            char lbr = editing ? '[' : ' ';
            char rbr = editing ? ']' : ' ';
            if (sh >= 100000)
                sprintf(rightbuf, "%c%6lu%c   ", lbr, (unsigned long)sh, rbr);
            else if (sh >= 10000)
                sprintf(rightbuf, "%c%5lu%c    ", lbr, (unsigned long)sh, rbr);
            else
                sprintf(rightbuf, "%c%4lu%c     ", lbr, (unsigned long)sh, rbr);
            VDP_setTextPalette(PAL3); /* cyan for share count */
            VDP_drawText(rightbuf, 30, row);
        } else {
            VDP_setTextPalette(PAL0);
            VDP_drawText(tickers[i].timestamp, 30, row);
            VDP_drawText("  ", 38, row); /* clear any leftover */
        }
    }
}

static void draw_price_panel(void)
{
    u8 i;
    for (i = 0; i < MAX_TICKERS; i++)
        draw_price_row(i);
    draw_net_worth();
}

/* -------------------------------------------------------------------------
 * draw_title()
 * ---------------------------------------------------------------------- */
static void draw_title(void)
{
    char title[42];
    sprintf(title, "[ MegaWifi Stock Ticker v%d.%d %s ]",
            (int)fw_major, (int)fw_minor, fw_variant);
    VDP_setTextPalette(PAL0);
    VDP_drawText(title, 0, 0);
    VDP_setTextPalette(PAL0);
    VDP_drawText("(c)2026 Mike Wolak", COPYRIGHT_COL, COPYRIGHT_ROW);
}

/* -------------------------------------------------------------------------
 * ticker_set_slot() — called by ticker_search.c when the user picks a ticker.
 * Replaces any slot (0-7) with the new symbol; resets price/validity.
 * Shares are preserved if the symbol changes (user may want to keep their count)
 * but reset to 0 if the slot was empty.
 * ---------------------------------------------------------------------- */
bool ticker_is_duplicate(const char *sym)
{
    u8 i, j;
    for (i = 0; i < MAX_TICKERS; i++) {
        const char *s = tickers[i].symbol;
        if (!s || s[0] == '\0') continue;
        for (j = 0; sym[j] && s[j] && sym[j] == s[j]; j++) {}
        if (sym[j] == '\0' && s[j] == '\0') return true;
    }
    return false;
}

void ticker_set_slot(u8 slot, const char *sym)
{
    u8 j;
    if (slot >= MAX_TICKERS) return;
    bool was_empty = (tickers[slot].symbol[0] == '\0');
    for (j = 0; j < 7 && sym[j]; j++) tickers[slot].symbol[j] = sym[j];
    tickers[slot].symbol[j] = '\0';
    tickers[slot].valid            = false;
    tickers[slot].price_cents      = 0;
    tickers[slot].prev_close_cents = 0;
    tickers[slot].timestamp[0]     = '\0';
    if (was_empty) tickers[slot].shares_owned = 0;
    update_ticker_pal(slot);
}

const char *ticker_get_slot_sym(u8 slot)
{
    return (slot < MAX_TICKERS) ? tickers[slot].symbol : "";
}

/* -------------------------------------------------------------------------
 * ticker_popup_redraw() — registered with ticker_search_init so the popup
 * can repaint the main display when it closes.
 * ---------------------------------------------------------------------- */
static void ticker_popup_redraw(void)
{
    u8 i;
    draw_title();
    draw_countdown(0);
    for (i = 0; i < MAX_TICKERS; i++)
        draw_price_row(i);
    draw_net_worth();
}

/* -------------------------------------------------------------------------
 * user_tsk()
 * ---------------------------------------------------------------------- */
static void user_tsk(void)
{
    while (1) mw_process();
}

/* -------------------------------------------------------------------------
 * megawifi_init()
 * ---------------------------------------------------------------------- */
static bool megawifi_init(void)
{
    char *variant = NULL;
    struct mw_ip_cfg dhcp_cfg = { {0}, {0}, {0}, {0}, {0} };
    enum mw_err err;

    if (mw_init(cmd_buf, MW_BUFLEN) != MW_ERR_NONE) return false;
    TSK_userSet(user_tsk);

    err = mw_detect(&fw_major, &fw_minor, &variant);
    if (err != MW_ERR_NONE) return false;
    if (variant) {
        uint8_t i;
        for (i = 0; i < sizeof(fw_variant_buf) - 1 && variant[i]; i++)
            fw_variant_buf[i] = variant[i];
        fw_variant_buf[i] = '\0';
    }

    err = mw_ap_cfg_set(AP_SLOT, AP_SSID, AP_PASS, MW_PHY_11BGN);
    if (err != MW_ERR_NONE) return false;

    err = mw_ip_cfg_set(AP_SLOT, &dhcp_cfg);
    if (err != MW_ERR_NONE) return false;

    err = mw_cfg_save();
    if (err != MW_ERR_NONE) return false;

    err = mw_ap_assoc(AP_SLOT);
    if (err != MW_ERR_NONE) return false;

    err = mw_ap_assoc_wait(30 * FPS);
    if (err != MW_ERR_NONE) return false;

    mw_sleep(3 * 60); /* stabilisation — critical */

    {
        const char *ntp[3] = { "0.pool.ntp.org", "1.pool.ntp.org", "2.pool.ntp.org" };
        mw_sntp_cfg_set("CST6CDT", ntp); /* US Central, auto DST */
    }

    return true;
}

/* -------------------------------------------------------------------------
 * main()
 * ---------------------------------------------------------------------- */
int main(bool hard_reset)
{
    u16 frame        = UPDATE_FRAMES;
    u8  ticker_cycle = 0;
    u8  i;

    /* --- Init ticker table with defaults -------------------------------- */
    for (i = 0; i < MAX_TICKERS; i++) {
        u8 j;
        for (j = 0; j < 7 && default_syms[i][j]; j++)
            tickers[i].symbol[j] = default_syms[i][j];
        tickers[i].symbol[j]        = '\0';
        tickers[i].price_cents      = 0;
        tickers[i].prev_close_cents = 0;
        tickers[i].valid            = false;
        tickers[i].timestamp[0]     = '\0';
        tickers[i].shares_owned     = 0;
        update_ticker_pal(i);
    }

    /* --- VDP setup ---------------------------------------------------- */
    VDP_setScreenWidth320();
    VDP_setPlaneSize(64, 32, TRUE);
    VDP_setScrollingMode(HSCROLL_TILE, VSCROLL_PLANE);
    VDP_clearPlane(BG_A, TRUE);
    VDP_clearPlane(BG_B, TRUE);

    /* --- Palette setup ------------------------------------------------ */
    PAL_setColor(0,  RGB24_TO_VDPCOLOR(0x000000)); /* VDP background = black */
    PAL_setColor(15, RGB24_TO_VDPCOLOR(0xFFFFFF)); /* PAL0: white  */
    PAL_setColor(31, RGB24_TO_VDPCOLOR(0x00CC00)); /* PAL1: green  */
    PAL_setColor(47, RGB24_TO_VDPCOLOR(0xFF2020)); /* PAL2: red    */
    PAL_setColor(63, RGB24_TO_VDPCOLOR(0x00AAFF)); /* PAL3: cyan   */
    VDP_waitVSync();

    /* --- NASDAQ tiled background (enable with -DBCKGND_ON) ------------ */
#ifdef BCKGND_ON
    init_nasdaq_bg();
#endif

    /* --- Initial title ------------------------------------------------ */
    VDP_setTextPalette(PAL0);
    VDP_drawText("[ MegaWifi Stock Ticker ]", 0, 0);
    VDP_setTextPalette(PAL0);
    VDP_drawText("(c)2026 Mike Wolak", COPYRIGHT_COL, COPYRIGHT_ROW);

    /* --- Joystick init ------------------------------------------------ */
    JOY_init();

    /* --- Register draw hook so mw_command() keeps display alive ------- */
    mw_set_draw_hook(fetch_draw_hook);

    /* --- Init ticker search popup (START button) ---------------------- */
    ticker_search_init(ticker_popup_redraw);

    /* --- WiFi init ---------------------------------------------------- */
    status_info("Connecting to WiFi...");
    if (!megawifi_init()) {
        status_err("WiFi init FAILED — halted");
        while (1) VDP_waitVSync();
    }

    draw_title();
    status_info("WiFi OK — waiting for NTP...");

    /* --- NTP sync — also accumulates RNG seed from frame count -------- */
    {
        int ntp_frames = 0;
        int max_frames = MS_TO_FRAMES(15000);
        char nbuf[42];
        while (ntp_frames < max_frames) {
            union mw_msg_sys_stat *ss = mw_sys_stat_get();
            if (ss && ss->dt_ok) break;
            VDP_waitVSync();
            rng_seed_ctr++;   /* count NTP-wait VBlanks toward seed */
            ntp_frames++;
        }
        if (ntp_frames >= max_frames) {
            sprintf(nbuf, "NTP timeout (%ds) — continuing", (int)(ntp_frames / 60));
            status_err(nbuf);
        } else {
            status_clear();
        }
    }

    /* --- Seed RNG and assign random share counts ----------------------
     * rng_seed_ctr has been accumulating since startup through both the
     * fetch_draw_hook (fires every VBlank during mw_command waits —
     * covers WiFi association + mw_sleep) and the NTP wait loop above.
     * The total count (typically 200-2000 frames) varies with AP timing,
     * providing enough entropy for a randomised starting position.
     * ------------------------------------------------------------------ */
    setRandomSeed(rng_seed_ctr);
    for (i = 0; i < MAX_TICKERS; i++) {
        /* Combine two u16 values to reach 1-100,000 range */
        u32 r = ((u32)random() << 16) | (u32)random();
        tickers[i].shares_owned = (r % 100000) + 1;
    }

    mw_http_cleanup(); /* pre-fetch cleanup */

    /* --- Initial fetch ------------------------------------------------ */
    for (i = 0; i < MAX_TICKERS; i++)
        fetch_quote(i);
    rebuild_marquee();
    draw_price_panel();

    draw_countdown(0);

    /* --- Main loop ---------------------------------------------------- */
    {
        u16 prev_joy = 0;
        while (1) {
            u16 joy, press;

            VDP_waitVSync();

            /* Scroll update MUST be first — must land in VBlank. */
            update_marquee_scroll();

            JOY_update();
            joy   = JOY_readJoypad(JOY_1);
            press = joy & ~prev_joy;
            prev_joy = joy;

            /* START: open ticker search for the selected row (or row 0). */
            if ((press & BUTTON_START) && !ticker_search_active()) {
                editing = false;
                ticker_search_open((u8)(selected >= 0 ? (u8)selected : 0));
            }

            /* Ticker search popup handles all input while open. */
            ticker_search_frame(press);

            if (ticker_search_active()) continue;

            /* ----- Selection and share-edit controls ----- */
            if (editing) {
                /* UP/DOWN ±100, LEFT/RIGHT ±1000, A ±1, B exit */
                if (press & BUTTON_UP) {
                    tickers[(u8)selected].shares_owned += 100;
                    draw_price_row((u8)selected);
                    draw_net_worth();
                } else if (press & BUTTON_DOWN) {
                    if (tickers[(u8)selected].shares_owned >= 100)
                        tickers[(u8)selected].shares_owned -= 100;
                    else
                        tickers[(u8)selected].shares_owned = 0;
                    draw_price_row((u8)selected);
                    draw_net_worth();
                } else if (press & BUTTON_RIGHT) {
                    tickers[(u8)selected].shares_owned += 1000;
                    draw_price_row((u8)selected);
                    draw_net_worth();
                } else if (press & BUTTON_LEFT) {
                    if (tickers[(u8)selected].shares_owned >= 1000)
                        tickers[(u8)selected].shares_owned -= 1000;
                    else
                        tickers[(u8)selected].shares_owned = 0;
                    draw_price_row((u8)selected);
                    draw_net_worth();
                } else if (press & BUTTON_A) {
                    tickers[(u8)selected].shares_owned += 1;
                    draw_price_row((u8)selected);
                    draw_net_worth();
                } else if (press & BUTTON_B) {
                    if (tickers[(u8)selected].shares_owned > 0)
                        tickers[(u8)selected].shares_owned -= 1;
                    draw_price_row((u8)selected);
                    draw_net_worth();
                } else if (press & BUTTON_C) {
                    editing = false;
                    draw_price_row((u8)selected);
                }
            } else {
                /* Selection mode: UP/DOWN move cursor, A enters edit mode */
                if (press & BUTTON_UP) {
                    u8 prev_sel = (u8)(selected >= 0 ? (u8)selected : 0);
                    selected = (s8)((selected <= 0) ? MAX_TICKERS - 1 : selected - 1);
                    draw_price_row(prev_sel);
                    draw_price_row((u8)selected);
                } else if (press & BUTTON_DOWN) {
                    u8 prev_sel = (u8)(selected >= 0 ? (u8)selected : MAX_TICKERS - 1);
                    selected = (s8)((selected < 0 || selected >= MAX_TICKERS - 1) ? 0 : selected + 1);
                    draw_price_row(prev_sel);
                    draw_price_row((u8)selected);
                } else if ((press & BUTTON_A) && selected >= 0) {
                    if (tickers[(u8)selected].symbol[0] != '\0') {
                        editing = true;
                        draw_price_row((u8)selected);
                    }
                }
            }

            /* Draw one ticker row per frame (rolling) — skip if we just
             * explicitly updated it above. */
            if (!editing)
                draw_price_row((u8)(frame % MAX_TICKERS));

            if ((frame % FPS) == 0)
                draw_countdown(frame);

            frame++;
            if (frame >= UPDATE_FRAMES) {
                frame = 0;
                fetch_quote(ticker_cycle);
                rebuild_marquee();
                draw_net_worth();
                ticker_cycle = (u8)((ticker_cycle + 1) % MAX_TICKERS);
                draw_countdown(frame);
            }
        }
    }

    return 0;
}
